apiVersion: messages.kubbee.tech/v1alpha1
kind: KafkaReference
metadata:
  name: kafkareference-odin
spec:
  clusterName: devel
  environment: odin
  tenant: odin
  kafkaClusterResource: 
    namespace: ccloud-cluster-operator-system
