# permissions for end users to edit kafkarbacs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkarbac-editor-role
rules:
- apiGroups:
  - messages.kubbee.tech
  resources:
  - kafkarbacs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - messages.kubbee.tech
  resources:
  - kafkarbacs/status
  verbs:
  - get
