# permissions for end users to view kafkaserviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkaserviceaccount-viewer-role
rules:
- apiGroups:
  - messages.kubbee.tech
  resources:
  - kafkaserviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - messages.kubbee.tech
  resources:
  - kafkaserviceaccounts/status
  verbs:
  - get
