# permissions for end users to view kafkarbacs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkarbac-viewer-role
rules:
- apiGroups:
  - messages.kubbee.tech
  resources:
  - kafkarbacs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - messages.kubbee.tech
  resources:
  - kafkarbacs/status
  verbs:
  - get
